#amazon

    ['alcatel', 'alcatel one touch']
    ['aqua', 'aqua craze 2', 'aqua power m']
    ['asus', 'asus zenfone']
    ['cables kart', 'cables kart tm']
    ['generic', 'generic (unbranded)']
    ['gionee', 'gionee f103 pro', 'gionee smart phone']
    ['gromic', 'gromic tm']
    ['htc', 'htc one']
    ['apple', 'i phone', 'iphone']
    ['huawei', 'huwai']
    ['karbon', 'karbonn']
    ['kechaoada', 'kechaoda', 'kechaoda k66(black)', 'kechoda']
    ['lemon', 'lemon mobiles']
    ['lg', 'lg mobiles']
    ['moto', 'moto g', 'motorola']
    ['mts', 'mts unlocked']
    ['micromax', 'micromax yu', 'macroma']
    oppo = ['oppo', 'oppo company', 'oppo digital']
    prix = ['prix', 'prixx']
    ['rage', 'rage mobiles']
    ['q reach', 'reach']?
    ['samsung', 'samsung note', 'samung']
    ['ui phones', 'ui phone']
    ['ulefone', 'ulefone armor']
    ['umi', 'uni']
    ['xiaomi', 'xiaomii']
    ['y king', 'y-king', 'yking']
    ['zen', 'zen mobiles']
