stop_list = [
#'Wearable Smart Devices>Smartwatches>Without Call Function',
'Computers>Storage>Internal HDD', 
'Computers>Storage>External HDD',
'Computers>Tablet Accessories>Memory Cards', 
'Computers>Storage>Pendrives',
'Mobiles>Mobile Accessories>Memory Cards',
'Mobiles>Mobile Accessories>OTG Pen Drives',
'Electronics>Cameras>Camera Accessories>Memory cards',
'Computers>Networking and Cables>Data Cards',
'Computers>Networking and Cables>Switches',
'Computers>Networking and Cables>Access Points',
'Computers>Networking and Cables>Wireless USB Adapters',
'Computers>Networking and Cables>Network Interface Cards',
'Computers>Networking and Cables>LAN Adapters',
'Computers>Networking and Cables>Cables',
'Computers>Networking and Cables>Routers',
'Mobiles>Mobile Accessories>Cables',
'Computers>Networking and Cables>Router Antennas & Boosters',
'Home Improvement>Home Automation & Safety>Appliance Safety & Outlet Controls>Switches & Dimmers',
'Electronics>Entertainment>Gaming consoles>Accessories>TV-out Cable Accessories',
'Audio & Video>Audio Accessories>Cables',
'Computers>Networking and Cables>Antenna Amplifiers',
'Electronics>Entertainment>Gaming Accessories>Cables & Adapters>Cables>Data Cables',
'Computers>Networking and Cables>Router UPS',
'Computers>Networking and Cables>Internal Modems',
'Computers>Tablet Accessories>Cables',
'Electronics>Appliances>Home Appliances>Voltage Stabilizers',
'Audio & Video>Audio Accessories>Remote Controllers',
'Musical Instruments>Studio/Stage Equipment & Accessories>Microphone>Microphone Accessories',
'Mobiles>Mobile Accessories>Headphones>Wired Headphones',
'Mobiles>Mobile Accessories>Screen Protectors',
'Electronics>Cameras>Camera Accessories', # nan ?
'Electronics>Entertainment>Audio & MP3 Players>Accessories>Microphones',
'Musical Instruments>Studio/Stage Equipment & Accessories>Microphone',
'Musical Instruments>Studio/Stage Equipment & Accessories>DJ Controller',
#'Electronics>Entertainment>TV & Video>Accessories>Media Players',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Soundbars',
'Computers>Laptop Accessories>Speakers',
'Audio & Video>Speakers>2.1 Speakers',
'Audio & Video>Speakers>5.1 Speakers',
'Audio & Video>Speakers>4.1 Speakers',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Voice Recorders',
'Mobiles>Mobile Accessories>Headsets',
'Computers>Laptop Accessories>Headsets',
'Electronics>Entertainment>Gaming Accessories>Headsets',
'Mobiles>Tablet Accessories>Headsets (Mic)',
'Mobiles>Mobile Accessories>Cases & Covers',
'Electronics>Entertainment>Audio & MP3 Players>Accessories>Headphones',
'Electronics>Entertainment>Audio & MP3 Players>Accessories>Headsets',
'Audio & Video>Audio Players & Recorders>Amplifier Receivers',
'Musical Instruments>Studio/Stage Equipment & Accessories>Amplifier Receivers',
'Audio & Video>Video Accessories>Video Glasses',
#'Wearable Smart Devices>Smart Glasses',
'Mobiles>Tablet Accessories>Screen Protectors',
'Home Decor>Clocks & Wall Decor>Wall Decor>Posters',
'Mobiles>Mobile Accessories>Screen Protectors>Samsung Galaxy On5',
'Mobiles>Mobile Accessories>Headsets>Headsets (Mic)',
'Mobiles>Mobile Accessories>Headphones',
'Mobiles>Mobile Accessories>Headphones>Bluetooth Headphones',
'Mobiles>Mobile Accessories>Screen Protectors>Redmi Note 4',
'Mobiles>Mobile Accessories>Headsets>Bluetooth Headsets (Mic)',
'Electronics>Entertainment>Gaming Accessories>Cables & Adapters>Cables>TV Out Cables',
'Musical Instruments>Studio/Stage Equipment & Accessories>Sound Mixers',
'Mobiles>Mobile Accessories>Screen Protectors>Lenovo Vibe K5 Note',
'Electronics>Entertainment>Audio & MP3 Players>MP3 Players>MP3 Players',
'Computers>Laptop Accessories>Headphones',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Speakers',
'Audio & Video>Speakers>2.0 Speakers',
'Mobiles>Mobile Accessories>Screen Protectors>Moto E3 Power',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Sound Mixers',
'Mobiles>Tablet Accessories>Bluetooth Headsets (Mic)',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Docks',
'Mobiles>Mobile Accessories',
'Electronics>Entertainment>Audio & MP3 Players',
#'Wearable Smart Devices>VR Controllers',
'Electronics>Entertainment>TV & Video>Accessories>Remote Controllers',
'Electronics>Entertainment>Audio & MP3 Players>Accessories>Microphones Accessories',
'Electronics>Entertainment>TV & Video>Accessories>Slingbox',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Speaker Mounts',
'Electronics>Entertainment>TV & Video>Accessories>Headsets',
'Musical Instruments>Accessories>Studio/Stage Equipment & Accessories>Studio>Headphones',
'Audio & Video>Video Accessories>Cables', 
'Mobiles>Tablet Accessories',
'Computers>Laptop Accessories>OTG Adapters',
'Electronics>Entertainment>Audio & MP3 Players>MP3 players/Ipods Accessories>Ipod Chargers',
'Pens & Stationery>Office Equipments>Public Address Systems',
'Electronics>Entertainment>Audio & MP3 Players>MP3 players/Ipods Accessories>Ipod Screen guards',
'Electronics>Entertainment>Audio & MP3 Players>MP3 players/Ipods Accessories>Headphones',
'Mobiles>Tablet Accessories>Headphones',
#'Wearable Smart Devices>Accessories>Smart Watch Screen Guards',
'Home Furnishing>Bed>Bedsheets',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Amplifiers & AV Receivers',
'Electronics>Entertainment>Cables', 
'Home Furnishing>Bed>Blankets',
'Pens & Stationery>Pens>Inks',
'Electronics>Entertainment>Gaming Accessories>Headphones',
'Health and Beauty>Hair Care>Conditioners',
#'Wearable Smart Devices>Smart Bands',
#'Wearable Smart Devices>Smartwatches>With Call Function',
#'Wearable Smart Devices>Smart Headphones',
'Wearable Smart Devices>Accessories>Smart Watch Straps',
#'Wearable Smart Devices>Smart Trackers',
'Mobiles>Mobile Accessories>Bluetooth Hats',
'Wearable Smart Devices>Accessories>Smart Band Straps',
#'Wearable Smart Devices>Bluetooth Item Finders',
#'Wearable Smart Devices>Smart Footwears',
#'Wearable Smart Devices>Smart Rings',
#'Wearable Smart Devices>Bluetooth Hats',
#'Wearable Smart Devices>Smart Jackets',
'Mobiles>Mobile Accessories>Smart Gloves',
'Lifestyle>Watches>Wrist Watches', 
#'Wearable Smart Devices>Smart Pendants',
'Toys>Educational Toys>Learning Toys',
'Mobiles>Mobile Accessories>Speakers',
'Electronics>Entertainment>Audio & MP3 Players>Accessories>Cables',
'Electronics>Entertainment>TV & Video>Accessories>Cables',
'Computers>Networking and Cables>Network Servers',
'[[{"nodeId":20001,"nodeName":"FLIPKART_TREE"}]]',
'[[{"node_id":20001,"node_name":"FLIPKART_TREE"}]]',
'Household>Bakeware>Weights & Measures>Kitchen Weights',
'Health and Beauty>Health Care>Health Care Devices>Weighing Scales',
'Household>Kitchen Tools>Weights & Measures>Kitchen Weights',
'Lifestyle>Leather & Travel Accessories>Luggage>Weighing Scales',
'Household>Kitchen Tools>Kitchen Implements>Hand Juicers',
'Computers>Computer Components',
'Computers>Computer Components>Internal Optical Drives',
'Home Improvement>Electricals>Adapters & Plugs>Spike Guard & Surge Protectors',
'Computers>Computer Components>Processors',
'Computers>Computer Components>Graphic Cards',
'Computers>Computer Accessories>Printer Covers',
'Computers>Computer Components>Combo Motherboards',
'Computers>Computer Components>Thermal Pastes',
'Computers>Computer Accessories>Spike Busters & Surge Protectors',
'Electronics>Entertainment>Gaming Accessories>Controllers>Mousepads',
'Computers>Computer Accessories>Hard Drive Enclosures',
'Computers>Computer Accessories>Barcode scanners',
'Computers>Computer Accessories>USB Gadgets',
'Computers>Computer Accessories>Monitor Arms',
'Computers>Computer Accessories>CPU Holders',
'Computers>Computer Accessories>Laptop Accessories Combos',
'Computers>Computer Accessories>Card Readers',
'Computers>Computer Accessories>UPS',
'Computers>Computer Accessories>Monitor & TV Covers',
'Computers>Computer Accessories>Pen Tablets',
'Computers>Computer Accessories>Laptop Skins & Decals',
'Computers>Storage>External HDD',
'Computers>Computer Components>KVM Consoles',
'Computers>Computer Accessories>Keyboard Skins',
'Computers>Computer Accessories>Computer Accessories Combos',
'Daily Essentials>Household Supplies>Home Cleaning>Toilet Cleaners',
'Daily Essentials>Household Supplies>Home Cleaning>Bathroom Floor Cleaners',
'Daily Essentials>Household Supplies>Home Cleaning>Kitchen Surface Cleaners',
'Household>Housekeeping & Laundry>Home Cleaning>Carpet & Upholstery Cleaners',
'Daily Essentials>Household Supplies>Laundry Supplies>Stain Removers',
'Household>Housekeeping & Laundry>Laundry>Liquid Detergents',
'Daily Essentials>Household Supplies>Kitchen Supplies>Dish Cleaning Gels',
'Daily Essentials>Household Supplies>Home Cleaning>Naphthalene Balls',
'Daily Essentials>Household Supplies>Home Cleaning>Drain Openers',
'Daily Essentials>Household Supplies>Kitchen Supplies>Dish Washer Detergents',
'Household>Housekeeping & Laundry>Laundry>Washing Powders',
'Daily Essentials>Household Supplies>Home Cleaning>Toilet Brushes',
'Daily Essentials>Household Supplies>Kitchen Supplies>Dish Detergents',
'Household>Housekeeping & Laundry>Laundry>Fabric Softeners',
'Daily Essentials>Household Supplies>Laundry Supplies>Fabric Deodorizers',
'Grocery>Household Care>Floor & Other Cleaners>Floor Cleaners',
'Household>Housekeeping & Laundry>Laundry>Detergent Pods',
'Household>Housekeeping & Laundry>Laundry>Machine Washing Powders',
'Household>Cookware>Pots & Pans>Pans & Tawas',
'Daily Essentials>Household Supplies>Kitchen Supplies>Dish Washing Bars',
'Mobiles>Mobile Accessories>Headphones>Wired Headphones',
'Mobiles>Mobile Accessories>Screen Protectors',
'Computers>Computer Accessories>Hard Drive Enclosures',
'Computers>Computer Accessories>Barcode scanners',
'Computers>Computer Accessories>USB Gadgets',
'Computers>Computer Accessories>Monitor Arms',
'Computers>Computer Accessories>CPU Holders',
'Computers>Computer Accessories>Laptop Accessories Combos',
'Computers>Computer Accessories>Card Readers',
'Computers>Computer Accessories>UPS',
'Computers>Computer Accessories>Monitor & TV Covers',
'Computers>Computer Accessories>Pen Tablets',
'Computers>Computer Accessories>Laptop Skins & Decals',
'Computers>Storage>External HDD',
'Computers>Computer Components>KVM Consoles',
'Computers>Computer Accessories>Keyboard Skins',
'Computers>Computer Accessories>Computer Accessories Combos',
'Computers>Computer Components>Motherboards',
'Electronics>Entertainment>Gaming Components>Coolers>Cabinets',
'Electronics>Entertainment>Gaming Components>Coolers>Processor',
'Electronics>Entertainment>Gaming Components>Coolers',
'Computers>Computer Components',
'Computers>Computer Components>Internal Optical Drives',
'Home Improvement>Electricals>Adapters & Plugs>Spike Guard & Surge Protectors',
'Computers>Computer Components>Processors',
'Computers>Computer Components>Graphic Cards',
'Computers>Computer Accessories>Printer Covers',
'Computers>Computer Components>Combo Motherboards',
'Computers>Computer Components>Thermal Pastes',
'Computers>Computer Accessories>Spike Busters & Surge Protectors',
'Electronics>Entertainment>Gaming Accessories>Controllers>Mousepads',
'Computers>Storage>Internal HDD',
'Computers>Computer Components>Internal Sound Cards',
'Daily Essentials>Household Supplies>Home Cleaning>Toilet Cleaners',
'Daily Essentials>Household Supplies>Home Cleaning>Bathroom Floor Cleaners',
'Daily Essentials>Household Supplies>Home Cleaning>Kitchen Surface Cleaners',
'Household>Housekeeping & Laundry>Home Cleaning>Carpet & Upholstery Cleaners',
'Daily Essentials>Household Supplies>Laundry Supplies>Stain Removers',
'Household>Housekeeping & Laundry>Laundry>Liquid Detergents',
'Daily Essentials>Household Supplies>Kitchen Supplies>Dish Cleaning Gels',
'Daily Essentials>Household Supplies>Home Cleaning>Naphthalene Balls',
'Daily Essentials>Household Supplies>Home Cleaning>Drain Openers',
'Daily Essentials>Household Supplies>Kitchen Supplies>Dish Washer Detergents',
'Household>Housekeeping & Laundry>Laundry>Washing Powders',
'Daily Essentials>Household Supplies>Home Cleaning>Toilet Brushes',
'Daily Essentials>Household Supplies>Kitchen Supplies>Dish Detergents',
'Household>Housekeeping & Laundry>Laundry>Fabric Softeners',
'Daily Essentials>Household Supplies>Laundry Supplies>Fabric Deodorizers',
'Grocery>Household Care>Floor & Other Cleaners>Floor Cleaners',
'Household>Housekeeping & Laundry>Laundry>Detergent Pods',
'Household>Housekeeping & Laundry>Laundry>Machine Washing Powders',
'Household>Cookware>Pots & Pans>Pans & Tawas',
'Daily Essentials>Household Supplies>Kitchen Supplies>Dish Washing Bars',
'Electronics>Entertainment>Gaming Accessories>Controllers>Motion Controllers>Other Platforms',
'Mobiles>Mobile Accessories>Chargers>Wall Chargers',
'Electronics>Entertainment>Gaming Accessories>Accessory kits',
'Electronics>Entertainment>Gaming Accessories>Accessory kits>PC',
'Electronics>Entertainment>Gaming Accessories>Cables & Adapters>Adapters',
'Electronics>Entertainment>Gaming Accessories>Cables & Adapters>Adapters>Non PC Compatible',
'Electronics>Entertainment>Gaming Accessories>Cases & Covers>Covers',
'Electronics>Entertainment>Gaming Accessories>Cases & Covers>Travel Cases',
'Electronics>Entertainment>Gaming Accessories>Cases & Covers',
'Electronics>Entertainment>Gaming Accessories>Controllers>Guns',
'Computers>Laptop Accessories>Adapters',
'Electronics>Cameras>Camera Accessories>Batteries',
'Electronics>Entertainment>Gaming Accessories>Controllers>Gamepads>Other Platforms',
'Electronics>Entertainment>Gaming Accessories>Controllers>Gamepads>PC',
'Gaming>Gaming Consoles>PSP' 'Gaming>Games>PC Games>Code in the box Games',
'Mobiles>Mobile Accessories>Batteries',
'Computers>Laptop Accessories>Keyboards',
'Electronics>Entertainment>Gaming Accessories>Charging Stations',
'Mobiles>Mobile Accessories>Chargers>Multi Pin Wall Charger',
'Mobiles>Mobile Accessories>Chargers',
'Electronics>Entertainment>Gaming Accessories>Cables & Adapters>Adapters>PC Compatible',
'Gaming>PS Vita>Games>Physical Games',
'Electronics>Entertainment>Gaming Accessories>Controllers>Motion Controllers>PC',
'Wearable Smart Devices>Accessories>Smart Watch Screen Guards',
'Gaming>PSP>Games>Physical Games',
'Gaming>Membership Cards',
'Gaming>Gaming Consoles>PS3',
'Electronics>Entertainment>Gaming Accessories>Controllers>Gamepads',
'Computers>Laptop Accessories>Cooling Pads/Cooling Stands',
'Electronics>Entertainment>Gaming Accessories>Game Control Mounts',
'Electronics>Cameras>Camera Accessories>Battery chargers',
'Apparels>Women>Ethnic Wear>Dress Materials',
'Games>Xbox One>Games>Physical Games',
'Electronics>Entertainment>Gaming Accessories>Controllers>Motion Controllers',
'Electronics>Entertainment>Gaming Accessories>Batteries & Chargers>Batteries',
'Games>Wii U>Games',
'Electronics>Entertainment>Gaming Accessories>Cases & Covers>Screen Guards',
'Mobiles>Mobile Accessories>Screen Protectors>Moto E3 Power',
'Gaming>Xbox One>Games>Code in the box Games',
'Gaming>Games>Xbox 360 Games>Code in the box Games',
'Electronics>Entertainment>Gaming Accessories>Controllers>Wearable Mice',
'Computers>Laptop Accessories>Keyboards>Touch Keyboards',
'Mobiles>Mobile Accessories>Screen Protectors>Redmi Note 4',
'Electronics>Entertainment>Gaming Accessories>Gaming Speakers',
'Electronics>Entertainment>Gaming Accessories>Headphones',
'Gaming>Wii U>Games>Physical Games',
'Electronics>Entertainment>Gaming Accessories>Batteries & Chargers>Chargers',
'Gaming>Games' 'Games>PC>Games>Physical Games',
'Grocery>Household Care>Basic Electricals>Batteries',
'Electronics>Entertainment>Gaming consoles',
'Mobiles>Mobile Accessories>Screen Protectors>Motorola Moto G5 plus',
'Gaming>Games>PS3 Games>Code in the box Games',
'Gaming>PS4>Games>Code in the box Games',
'Mobiles>Tablet Accessories>Keyboards',
'Mobiles>Mobile Accessories>Power Banks',
'Gaming>Gaming VR',
'Gaming>PC>Games>Code in the box Games', 
'Gaming>Gaming Consoles>Wii U',
'Electronics>Entertainment>Gaming Accessories>Controllers>Mouse Bungee',
'Electronics>Entertainment>Gaming Accessories>Gaming Accessories Combo',
'Electronics>Health and Personal Care>Health Care>Digital Thermometers',
'Gaming>DS>Consoles' 'Gaming>Xbox 360>Consoles',
'Electronics>Entertainment>Gaming consoles>Handheld Consoles',
'Gaming>Gaming Consoles>Handheld Consoles', 
'Gaming>Xbox One>Consoles',
'Gaming>Wii>Consoles', 
'Gaming>Gaming Consoles>PS4',
'Gaming>Gaming Consoles>PS2',
'Electronics>Entertainment>Gaming Accessories>Controllers>Keyboards',
'Electronics>Entertainment>Gaming Accessories>Controllers>Joysticks and Gaming Wheels>Other Platforms',
'Electronics>Entertainment>Gaming Accessories>Controllers>Joysticks and Gaming Wheels>PC',
'Electronics>Entertainment>Gaming Accessories>Controllers>Joysticks and Gaming Wheels',
'Electronics>Entertainment>Gaming Accessories>Controllers>Mouse',
'Computers>Laptop Accessories>Mice', 
'Gaming>Wii>Games>Physical Games',
'Gaming>3DS>Games>Physical Games', 
'Gaming>DS>Games>Physical Games',
'Gaming>PC>Games>Physical Games',
'Gaming>Games>PS2 Games>PS2 Physical Games',
'Gaming>Games>PS3 Games>PS3 Physical Games',
'Gaming>Xbox 360>Games>Physical Games',
'Gaming>Games>PS4 Games>PS4 Physical Games',
'Gaming>Xbox One>Games>Physical Games',
'Computers>Laptop Accessories>Batteries', 
'Gaming>Gaming Consoles>PSP',
'Gaming>Games>PC Games>Code in the box Games', 
'Gaming>Games',
'Games>PC>Games>Physical Games', 
'Gaming>PSP>Games>Code in the box Games',
'Games', 
'Games>Xbox 360>Games', 
'Games>PS3>Games',
'Gaming>Wii>Games>Code in the box Games',
'Computers>Computer Components>RAMs',
'Electronics>Cameras>Camera Accessories>Filters',
'Mobiles>Mobile Accessories>Cases & Covers>Designer Cases & Covers',
'Mobiles>Mobile Accessories>Screen Protectors>Mi Redmi Note 4',
'Mobiles>Mobile Accessories>Screen Protectors>Motorola Moto E3 Power',
'Gaming>DS>Consoles', 
'Gaming>Xbox 360>Consoles',
'Household>Storage>Containers & Jars>Kitchen Containers',
'Audio & Video>Speakers',
'Audio & Video>Video Players & Recorders>DVD/Blueray Players',
'Audio & Video>Video Players & Recorders>Media Streaming Devices',
'Computers',
'Computers>Computer Peripherals>Monitors',
'Computers>Desktop PCs>All In One PCs',
'Computers>Desktop PCs>Mini PCs',
'Electronics>Entertainment',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Boom Box',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>FM Radio',
'Electronics>Entertainment>Audio & MP3 Players>Home Audio>Hi-Fi Systems',
'Mobiles',
]

