urls = [
{'url': 'https://www.tatacliq.com/electronics-tablets/c-msh1211', 'items': 286, 'pages': 16},
{'url': 'https://www.tatacliq.com/electronics-mobile-phones/c-msh1210/', 'items': 1384, 'pages': 62},
{'url': 'https://www.tatacliq.com/electronics-tv/c-msh1216', 'items': 1143, 'pages': 52},
{'url': 'https://www.tatacliq.com/electronics-large-appliances/c-msh1214', 'items': 1453, 'pages': 65},
{'url': 'https://www.tatacliq.com/electronics-air-conditioner/c-msh1230', 'items': 824, 'pages': 39},
{'url': 'https://www.tatacliq.com/electronics-wearable-devices/c-msh1219', 'items': 406, 'pages': 21},
{'url': 'https://www.tatacliq.com/electronics-camera/c-msh1220', 'items': 1640, 'pages': 73},
{'url': 'https://www.tatacliq.com/electronics-laptop/c-msh1223', 'items': 948, 'pages': 44},
{'url': 'https://www.tatacliq.com/electronics-kitchen-appliances/c-msh1229', 'items': 1630, 'pages': 72},
{'url': 'https://www.tatacliq.com/electronics-small-appliances/c-msh1231', 'items': 420, 'pages': 22},
{'url': 'https://www.tatacliq.com/electronics-personal-care/c-msh1236', 'items': 1010, 'pages': 47},
{'url': 'https://www.tatacliq.com/electronics-storage-devices/c-msh1228', 'items': 432, 'pages': 23},
{'url': 'https://www.tatacliq.com/electronics-accessories/c-msh1222', 'items': 17593, 'pages': 738},
]