urls = [
"https://www.snapdeal.com/products/electronic-tv-accessories?sort=plrty",
##"https://www.snapdeal.com/products/electronics-speakers?sort=plrty",
##"https://www.snapdeal.com/products/electronic-headphones-earphones?sort=plrty",
##"https://www.snapdeal.com/products/electronic?sort=plrty", #
#####"https://www.snapdeal.com/products/appliances-large?sort=plrty", #
"https://www.snapdeal.com/products/appliances-washing-machines-dryers?sort=plrty",
"https://www.snapdeal.com/products/appliances-air-conditioners?sort=plrty",
"https://www.snapdeal.com/products/appliances-fans-air-coolers?sort=plrty",
"https://www.snapdeal.com/products/appliances-refrigerator?sort=plrty",
"https://www.snapdeal.com/products/appliances-microwave-ovens-otgs?sort=plrty",
"https://www.snapdeal.com/products/appliances-fans?sort=plrty",
"https://www.snapdeal.com/products/appliances-ups-stabilizers?sort=plrty",
"https://www.snapdeal.com/products/appliances-geysers-immersion-rods?sort=plrty",
"https://www.snapdeal.com/products/appliances-solar?sort=plrty",
#####
"https://www.snapdeal.com/products/office-equipment?sort=plrty", #
#####"https://www.snapdeal.com/products/appliances-home?sort=plrty", #
"https://www.snapdeal.com/products/appliances-iron?sort=plrty",
"https://www.snapdeal.com/products/appliances-outdoor-utility-appliances?sort=plrty",
"https://www.snapdeal.com/products/appliances-vacuum-cleaners?sort=plrty",
"https://www.snapdeal.com/products/appliances-air-purifiers-humidifiers?sort=plrty",
"https://www.snapdeal.com/products/appliances-dishwashers?sort=plrty",
"https://www.snapdeal.com/products/appliances-ultra-sonic-cleaners?sort=plrty",
"https://www.snapdeal.com/products/iron-garment-steamers?sort=plrty",
"https://www.snapdeal.com/products/appliances-home-security?sort=plrty", # 3373
#####
#####"https://www.snapdeal.com/products/appliances-personal-care-appliances?sort=plrty", #
"https://www.snapdeal.com/products/trimmers?sort=plrty",
"https://www.snapdeal.com/products/shavers?sort=plrty",
"https://www.snapdeal.com/products/clippers?sort=plrty",
"https://www.snapdeal.com/products/grooming-kits?sort=plrty",
"https://www.snapdeal.com/products/body-groomers?sort=plrty",
"https://www.snapdeal.com/products/hair-straightners?sort=plrty",
"https://www.snapdeal.com/products/hair-dryers?sort=plrty",
"https://www.snapdeal.com/products/hair-stylers?sort=plrty",
"https://www.snapdeal.com/products/epilators?sort=plrty",
"https://www.snapdeal.com/products/facial-care?sort=plrty",
#####
#####"https://www.snapdeal.com/products/cameras?sort=plrty",
"https://www.snapdeal.com/products/cameras-digital-slrs?sort=plrty",
"https://www.snapdeal.com/products/cameras-digital-cameras?sort=plrty",
#"https://www.snapdeal.com/products/cameras-lenses?sort=plrty",
#"https://www.snapdeal.com/products/cameras-selfie-sticks?sort=plrty",
#"https://www.snapdeal.com/products/cameras-camera-accessories?sort=plrty",
"https://www.snapdeal.com/products/cameras-binoculars-telescopes?sort=plrty",
"https://www.snapdeal.com/products/cameras-camcorders?sort=plrty",
#"https://www.snapdeal.com/products/cameras-digital-photo-frames?sort=plrty",
#####
#####"https://www.snapdeal.com/products/mobiles-mobile-phones?sort=plrty", #
"https://www.snapdeal.com/products/mobiles-mobile-phones?sort=plrty",
"https://www.snapdeal.com/products/mobiles-tablets?sort=plrty",
#"https://www.snapdeal.com/products/mobiles-accessories?sort=plrty",
#"https://www.snapdeal.com/products/mobiles-tablet-accessories?sort=plrty",
"https://www.snapdeal.com/products/mobile-insurance-warranty?sort=plrty",
"https://www.snapdeal.com/products/refurbished-mobiles?sort=plrty",
"https://www.snapdeal.com/products/refurbished-tablets?sort=plrty",
"https://www.snapdeal.com/products/refurbished-used-mobiles?sort=plrty",
#"https://www.snapdeal.com/products/mobile-services?sort=plrty",
"https://www.snapdeal.com/products/mobiles-featured-phones?sort=plrty",
#####
#"https://www.snapdeal.com/products/refurbished-mobiles?sort=plrty", #
#"https://www.snapdeal.com/products/mobiles-tablets?sort=plrty", #
#"https://www.snapdeal.com/products/mobiles-accessories?sort=plrty", #
#"https://www.snapdeal.com/products/mobiles-cases-covers?sort=plrty", #
#"https://www.snapdeal.com/products/mobiles-power-banks?sort=plrty", #
#"https://www.snapdeal.com/products/mobiles-wearables-smartwatches?sort=plrty", #
"https://www.snapdeal.com/products/computers-laptops?sort=plrty", #
"https://www.snapdeal.com/products/computers-printers-scanners?sort=plrty", #
"https://www.snapdeal.com/products/storage-devices?sort=plrty", #
"https://www.snapdeal.com/products/computers-routers-modems?sort=plrty", #
"https://www.snapdeal.com/products/office-equipment?sort=plrty", #
#"https://www.snapdeal.com/products/computers-computer-accessories?sort=plrty", #
"https://www.snapdeal.com/products/computers-desktops?sort=plrty", #
#"https://www.snapdeal.com/products/gaming?sort=plrty", #
#"https://www.snapdeal.com/products/computers-components?sort=plrty", #
#"https://www.snapdeal.com/products/computers-software-cd-roms?sort=plrty", #
"https://www.snapdeal.com/products/computers-monitors?sort=plrty", #
]
