#encoding: utf8

groups = [
##"All Videos",
##"Movies",
##"TV Shows",
##"Kids Shows",
#"Amazon Fire TV Stick",
#"Amazon Prime Video",
#"Fire TV Apps & Games",
#"All-New Kindle",
##"Kindle Paperwhite",
##"Kindle Voyage",
##"Kindle Oasis",
##"Kindle E-reader Accessories",
#"See all Kindle E-readers",
##"Free Kindle Reading Apps",
##"Kindle Cloud Reader",
##"Manage Your Content and Devices",
##"All Kindle eBooks",
##"Kindle Unlimited",
##"Kindle Monthly Deals",
##"eBook Bestsellers",
##"eBooks in Indian Languages",
##"Hindi",
##"Tamil",
##"Marathi",
##"Amazon Shopping App",
##"Free Kindle Reading Apps",
##"Amazon Now",
##"All Books",
##"Amazon Best Reads",
##"New Releases & Pre-orders",
##"Bestsellers",
##"Literature & Fiction",
##"Children's & Young Adult",
##"Books by Indian Authors",
##"Textbooks",
##"Exam Central",
#"Kindle eBooks",
##"Educational Software",
##"Used Books",
##"Books in Global Store",
##"Books in Indian Languages",
##"Hindi",
##"Marathi",
##"Tamil",
##"All Movies & TV Shows",
##"Blu-ray",
##"All English",
##"All Hindi",
##"All Consoles, Games & Accessories",
#"PC Games",
##"Pre-orders & New Releases",
#"Consoles",
##"Accessories",
##"All Music",
##"International Music",
##"Film Songs",
##"Indian Classical",
##"Musical Instruments",
"All Mobile Phones",
#"Smartphones", # 4063
#"Android Mobiles", # 1973
#"Windows Mobiles", # 45
#"Used & Refurbished Mobiles", # 577
##"All Mobile Accessories",
##"Cases & Covers",
##"Screen Protectors",
#"Power Banks",
##"All Electronics",
#####"All Tablets", # 6908
##"Tablet Accessories",
#"Landline Phones", # 1392
#"Wearable Devices",
#"All Computers & Accessories",
#"Laptops", # 4181
#"Desktops & Monitors", # 5442
#"Pen Drives",
#"Hard Drives",
#"Memory Cards",
#####"Printers & Ink", # 15702
#"Networking & Internet Devices",
##"Computer Accessories",
##"Software",
##"All Electronics",
##"All Office & Stationery",
##"Pens & Writing",
##"Art & Craft Supplies",
#####"Office Electronics", # 20203
##"Amazon for Business",
#"All Cameras & Photography",
#"Digital SLRs", # 298
#"Point & Shoot Cameras", # 832
##"Lenses",
##"Camera Accessories",
#####"Security & Surveillance", # 17917
##"Binoculars & Telescopes",
#####"Camcorders", # 4547
##"All Musical Instruments",
#"Musical Instrument Accessories",
#####"Professional Audio & Recording", # 14433
#"All Electronics",
#"Televisions", # 1283
#"Headphones",
#"Speakers",
#####"Home Entertainment Systems", # 40782
#"MP3 & Media Players",
##"Audio & Video Accessories",
#"All Audio & Video",
#"All Home & Kitchen",
#####"Kitchen & Home Appliances", # 86963
#####"Large Appliances", # 50725
##"Kitchen & Dining",
##"Furniture",
##"Décor & Lighting",
##"Home Furnishing",
##"Home Improvement",
##"Garden & Outdoors",
##"Amazon for Business",
##"All Pet Supplies",
##"Dogs",
##"Cats",
##"Birds",
##"Fish & Aquatics",
##"Small Animals",
##"All Toys & Games",
##"Puzzles",
##"Soft Toys",
##"Die-Cast & Toy Vehicles",
##"Learning & Education",
##"All Baby Products",
##"Diapers, wipes & more",
##"Baby bath, skin & grooming",
##"Strollers & Prams",
##"Nursing & Feeding",
##"Amazon Family",
##"Baby Wish List",
##"All Sports, Fitness & Outdoors",
##"Exercise & Fitness",
##"Camping & Hiking",
##"Cycling",
##"Cricket",
##"Badminton",
##"Swimming",
##"Motorbiking Accessories",
##"Golf",
##"Fan Shop",
##"Football",
##"Tennis",
##"Running",
##"All Beauty",
##"Luxury Beauty",
##"Fragrance",
##"All Health",
##"Diet & Nutrition",
##"Household Supplies",
##"Personal Care Appliances",
##"Health Care Devices",
##"Men's Grooming",
##"Subscribe & Save",
##"All Grocery & Gourmet Foods",
##"Coffee, Tea & Beverages",
##"Snack Foods",
##"Amazon Pantry",
##"Women's Clothing",
##"Men's Clothing",
##"Kids' Clothing",
##"Women's Intimate Apparel",
##"Men's Innerwear",
##"All Accessories",
##"Offers on Clothing",
##"All Clothing & Accessories",
##"Amazon Fashion",
##"All Watches",
##"Men's Watches",
##"Women's Watches",
##"Premium Watches",
##"Deals on Watches",
##"Watches in Global Store",
##"Men's Sunglasses",
##"Women's Sunglasses",
##"Spectacle Frames",
##"All Sunglasses",
##"Amazon Fashion",
##"All Jewellery",
##"Women's Jewellery",
##"Men's Jewellery",
##"Precious Jewellery",
##"Fashion Jewellery",
##"Traditional Jewellery",
##"Fresh & Trending Jewellery",
##"Gift Store",
##"Gold & Silver Coins",
##"Sales & Deals",
##"All Handbags & Clutches",
##"Handbags",
##"Clutches",
##"Totes",
##"Sling Bags",
##"Women's Wallets",
##"Premium Bags",
##"Leather Bags",
##"Sales & Deals",
##"Amazon Fashion",
##"All Bags, Wallets and Luggage",
##"Backpacks",
##"Messenger Bags",
##"Laptop Bags",
##"Men's Wallets",
##"Luggage",
##"Travel Accessories",
##"Sales & Deals",
##"All Men's Shoes",
##"Formal Shoes",
##"Sports & Outdoor",
##"Loafers & Mocassins",
##"Sneakers",
##"Sandals & Floaters",
##"Flip-flops",
##"Kids' Shoes",
##"Shoe Care & Accessories",
##"Sales & Deals",
##"All Shoes",
##"Amazon Fashion",
##"All Women's Shoes",
##"Pumps & Peeptoes",
##"Fashion Sandals",
##"Casual Slippers",
##"Ballet Flats",
##"Sports & Outdoor",
##"Shoes in Global Store",
##"All Cars & Bikes",
##"Car & Bike Care",
##"Lubricants",
##"Helmets",
##"Gloves",
##"Bike Accessories",
##"Bike Parts",
##"Air Fresheners",
##"Car Accessories",
##"Car Electronics",
##"Car Parts",
##"Car Tyres & Tyre Accessories",
##"All Industrial Supplies",
##"Lab & Scientific",
##"Janitorial & Sanitation Supplies",
##"Test, Measure & Inspect",
##"All Used & Refurbished",
##"Books",
#"Mobiles", # 586
#"Laptops", # 3647
#"Tablets", # 6933
##"Sell your Used Items",
]
