urls = [
{'total_items': 130633, 'second_url': u'http://www.ebay.in/sch/Audio-Home-Entertainment/293/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Audio-Home-Entertainment/293/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Audio & Home Entertainment', 'pages': 2662},
{'total_items': 90439, 'second_url': u'http://www.ebay.in/sch/Cameras-Optics/625/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Cameras-Optics/625/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Cameras & Optics', 'pages': 1858},
{'total_items': 90442, 'second_url': u'http://www.ebay.in/sch/Cameras-Optics/625/i.html?_from=R40&_nkw=&_pgn=3&_skc=100&rt=nc', 'first_url': u'http://www.ebay.in/sch/Cameras-Optics/625/i.html?_from=R40&_nkw=&_pgn=3&_skc=100&rt=nc', 'cat_name': u'Home & Kitchen Appliances', 'pages': 1858},
{'total_items': 546224, 'second_url': u'http://www.ebay.in/sch/Laptops-Computer-Peripherals/160/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Laptops-Computer-Peripherals/160/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Laptops & Computer Peripherals', 'pages': 10974},
{'total_items': 3945, 'second_url': u'http://www.ebay.in/sch/LCD-LED-Televisions/11071/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/LCD-LED-Televisions/11071/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'LCD, LED & Televisions', 'pages': 128},
{'total_items': 16237, 'second_url': u'http://www.ebay.in/sch/Memory-Cards-Pen-Drives-HDD/162260/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Memory-Cards-Pen-Drives-HDD/162260/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Memory Cards, Pen Drives & HDD', 'pages': 374},
{'total_items': 1411873, 'second_url': u'http://www.ebay.in/sch/Mobile-Accessories/14416/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Mobile-Accessories/14416/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Mobile Accessories', 'pages': 28287},
{'total_items': 10430, 'second_url': u'http://www.ebay.in/sch/Mobile-Phones/15032/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Mobile-Phones/15032/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Mobile Phones', 'pages': 258},
{'total_items': 123948, 'second_url': u'http://www.ebay.in/sch/Tablets-Accessories/178741/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Tablets-Accessories/178741/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Tablets & Accessories', 'pages': 2528},
{'total_items': 6760, 'second_url': u'http://www.ebay.in/sch/Wearable-Devices/180544/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Wearable-Devices/180544/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Wearable Devices', 'pages': 185},
]