urls = [
{'total_items': 136744, 'second_url': u'http://www.ebay.in/sch/Audio-Home-Entertainment/293/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Audio-Home-Entertainment/293/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Audio & Home Entertainment', 'pages': 2784},
{'total_items': 91750, 'second_url': u'http://www.ebay.in/sch/Cameras-Optics/625/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Cameras-Optics/625/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Cameras & Optics', 'pages': 1885},
{'total_items': 27162, 'second_url': u'http://www.ebay.in/sch/Home-Kitchen-Appliances/20710/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Home-Kitchen-Appliances/20710/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Home & Kitchen Appliances', 'pages': 593},
{'total_items': 724605, 'second_url': u'http://www.ebay.in/sch/Laptops-Computer-Peripherals/160/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Laptops-Computer-Peripherals/160/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Laptops & Computer Peripherals', 'pages': 14542},
{'total_items': 3956, 'second_url': u'http://www.ebay.in/sch/LCD-LED-Televisions/11071/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/LCD-LED-Televisions/11071/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'LCD, LED & Televisions', 'pages': 129},
{'total_items': 17489, 'second_url': u'http://www.ebay.in/sch/Memory-Cards-Pen-Drives-HDD/162260/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Memory-Cards-Pen-Drives-HDD/162260/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Memory Cards, Pen Drives & HDD', 'pages': 399},
{'total_items': 11758, 'second_url': u'http://www.ebay.in/sch/Mobile-Phones/15032/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Mobile-Phones/15032/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Mobile Phones', 'pages': 285},
{'total_items': 126033, 'second_url': u'http://www.ebay.in/sch/Tablets-Accessories/178741/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Tablets-Accessories/178741/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Tablets & Accessories', 'pages': 2570},
{'total_items': 6939, 'second_url': u'http://www.ebay.in/sch/Wearable-Devices/180544/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'first_url': u'http://www.ebay.in/sch/Wearable-Devices/180544/i.html?_from=R40&_nkw=&_pgn=2&_skc=50&rt=nc', 'cat_name': u'Wearable Devices', 'pages': 188},
]